version: '2'
services:
    app:
        restart: always
        build: flaskr
        environment:
            PG_HOST: postgres
        expose:
        - 5000
        depends_on:
        - postgres

    proxy:
        restart: always
        build: server
        ports:
        - '80:80'
        depends_on:
        - app

    data:
        image: postgres:latest
        volumes:
        - /var/lib/postgresql
        command: "true"

    postgres:
        restart: always
        build: ./dbserver
        volumes_from:
        - data
        ports:
        - "5433:5432"
